

#DB configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appsdeveloperblogs
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: on
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



  #Swagger configurations
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: on
#Actuctor Configurations
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,beans,env,customactuator
  info:
    env:
      enabled: on
    build:
      enabled: on
    git:
      enabled: on
    java:
      enabled: on
    os:
      enabled: on
server:
  port: 8080